name: nwb_datajoint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=2.*
  - nodejs=12.4.*
  - pydotplus>=2.0.*
  - dask>=2.30
  - pip>=20.2.*
  - pip:
    - hither>=0.4.*
    - ml-ms4alg>=0.3.*
    - spikeinterface==0.10.*
    - pynwb>=1.4
    - datajoint==0.12.*
    - pymysql>=1.0.*
    - h5py==2.10.*
    - git+git://github.com/laboratorybox/labbox-launcher
    - git+git://github.com/LorenFrankLab/ndx-franklab-novela
